### ISSUE TITLE
Suggest author can put some prebuilt binary there, so ppl can use that directly

### ISSUE THREAD

**Issue by paradise321** [bitdata/ocrtable#1]
Hi buddy,

Good job! And suggest you can put some **prebuilt binary files** (.exe with necessary DLLs) there as release, so others can directly use it without recompiling themseleves.

Thanks!

建议兄弟把预编译好的二进制包（包含可独立运行的exe及必须的DLL文件）放在releases或者啥地方，方便其他人不用再编译就能直接下载并使用，谢谢！

**Comment by finchcn** [comment]
建议依赖的库直接包含进去，自己编译Tesseract等库还是比较复杂的

**Comment by bitdata** [comment]
OK. I'll do it later.

**Comment by bitdata** [comment]
You can download now.

**Comment by paradise321** [comment]
Thanks a lot!

**Comment by paradise321** [comment]
I saw the link of "Download pre-compiled components", is that possible to put it to the release part? Maybe that's a more formal way :).

https://github.com/bitdata/ocrtable/releases

**Comment by bitdata** [comment]
Sorry. The release part is more than 100M bytes and is not convenient for github to manage.

**Comment by paradise321** [comment]
Ok, understand and I will close this issue:)
